### ISSUE TITLE
Should <select> anatomy include type-to-search?

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#145]
I've seen "typeahead' used to mean a few slightly different things, so in this issue I'm specifically talking about this behavior/functionality:

- When the `<select>` is focused (either open or closed), if the user types characters, these are collected in a buffer and selection jumps to the next `<option>` following the currently selected `<option>` that matches the text in the buffer (there may be some subtleties here that I am eliding for the purposes of this discussion).
- After some timeout with no more characters (short, maybe 0.5s) the buffer is cleared.
- The select has a button, not a textfield, so the buffer contents are not visible except as they are reflected in the changing selection.
- The `<option>`s are not filtered; typing makes the selection jump around but does not hide non-matching `<option>`s.

This behavior is present on the default `<select>` in desktop Chromium, Firefox, and Safari (there are some subtle differences but they are mostly the same).  I tried it on a few design systems ([Ant Design](https://ant.design/components/select/), [Carbon](https://www.carbondesignsystem.com/components/select/code/), [Atlas](https://atlaskit.atlassian.com/packages/core/select)) and the only one I saw that had this functionality was Carbon but that's because they build on the native `<select>`.

We should consider including this behavior in the `<select>` anatomy.  If we don't do so, implementers would probably include it in their controller code for [Custom Select](https://github.com/MicrosoftEdge/MSEdgeExplainers/blob/main/ControlUICustomization/explainer.md) anyway, because not to do so would mean that custom selects would less accessible and less generally convenient than native `<select>`s.  This behavior is a big time-saver for typical `<select>` use cases like choosing one's country or state from a long list of `<option>`s. 

It's more complicated than the other `<select>` "controller code" we have defined so far, but I think it's worth including.  The fact that it's  not trivial means that it's less likely that developers rolling their own implementations would include this functionality, and I think that the lack of it in several major component frameworks is proof of this.

**Comment by gregwhitworth** [comment]
@dandclark this was discussed in [104](https://github.com/WICG/open-ui/issues/104#issuecomment-646368756) and there was agreement to do this as every solution does this in some way. I'd recommend a concrete proposal for the default type ahead (this may need to be UA defined).

Also, I'd recommend also resolving that the anatomy should have an input since it takes user keyboard input. So I think the proposal would be:

1. Concrete proposal for default type ahead (eg: does it filter by default, if not how will that be done?)
2. Input should be in the anatomy rather than a button alone (given research)

**Comment by dandclark** [comment]
I'll create a PR (though I may not get to it before this week's sync) proposing an addition to the anatomy.  I agree that some parts of it will probably need to be UA defined, e.g. the specific timeout value before the character buffer resets.  But we can outline at least the general behavior.

To me this version of typeahead is fully distinct from the mode of operation where there is a visible text input and the options are filtered.  If we want to include the text-input-plus-filtering dropdown scenario (like with [`<datalist>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/datalist)) in the `<select>` anatomy it seems like it should be a separate mode, sort of like `<select multiple>`.  The type-ahead in that mode would be different in these ways:
- The typed text is visible to the user (because the button has been replaced by a text input)
- Typing doesn't change the selected option, instead it filters the options list
- There is no timeout where the "buffer" is cleared and the typed characters reset

We can add this combobox-like mode to the anatomy if that is the consensus, but I think that should be separate from the addition of type-to-select in "normal" [`<select>`](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/select) mode; the functionality is quite different even if we call both things "typeahead".

**Comment by una** [comment]
I believe we agreed to keep this and turn it on as an optional attribute

**Comment by mfreed7** [comment]
There are two "modes" being discussed: I'll call the [first one](https://github.com/WICG/open-ui/issues/145#issue-666667172) "typeahead" and the [second one](https://github.com/WICG/open-ui/issues/145#issuecomment-665274032) "filtering".

In my opinion (and I'd love UX expert feedback on this), the "typeahead" mode is violently user-hostile. Without data to back me up, I would guess this feature is not widely used. Because the typeahead buffer is invisible **and** resets itself after a magic timeout, and additionally because it only searches verbatim from the **start** of each option, this feature is very difficult to use effectively. It likely works well only for touch typists who make no mistakes. I'm guessing this is why the design systems don't implement this mode of input.

Given the above, and assuming we're moving towards a new element type (e.g. `<combobox>`), do we need to specify the "typeahead" mode of operation at all? I **do** think we should specify the "filtering" mode, as that is more user friendly, and more common on third party select controls. Is there a real use case that is not completely served by "filtering" mode?

**Comment by dandclark** [comment]
I agree with the points about "typeahead" being user-unfriendly and probably not used much.  Is it worse to have it than not to have it though?  Personally I would miss it; I use it regularly, e.g. for a `<select>` with a list of US states, typing the first two letters of my state is quicker than reaching it otherwise.  That's just me though, I too would love to get more UX expert feedback here. :)

My mental model is that "typeahead" mode is for discrete lists of options (e.g. US states) and that "filtering" mode is for lists where the user can supply their own value, e.g. a messaging app's "To" box which has a filtered dropdown of the user's contacts, but where the user can enter a value not in their contacts list.

A "filtering" select could also be used such that the form isn't submittable until the user chooses a value from an `<option>`, e.g. maybe a mode where the `validity` state is false until one of the `<option>`s is chosen.  But with the textbox present, there is less of a clear indicator of when arbitrary values are allowed or not.  With "typeahead" select it's obvious given the UI that the user can't supply their own values.

If we could find a nice way to remove ambiguity in the UI such that the author can tell whether a "filtering" select allows custom values or not, I would agree that the "typeahead" mode has less value.

**Comment by dandclark** [comment]
FWIW, from ARIA best practices https://w3c.github.io/aria-practices/#listbox_kbd_interaction:
>- Type-ahead is recommended for all listboxes, especially those with more than seven options:
>   - Type a character: focus moves to the next item with a name that starts with the typed character.
>   - Type multiple characters in rapid succession: focus moves to the next item with a name that starts with the string of characters typed.

Further suggests to me that we should have this behavior, assuming we don't scrap "typeahead" mode of operation altogether in favor of the filtering textbox mode.

**Comment by mfreed7** [comment]
Thanks for the comments. I should have clarified one important thing: I really think we should specify the "filtering" mode, and have it **enabled** by default. It is my belief that in almost all cases, "filtering" mode gives the same or better usability in all of the same situations. It might need a few additional options that would be helpful:
 1. Auto-focus the first filtered element
 2. Allow the specification of filtering method: option text must **start** with the search text, search text must be **contained** within the option text, search text must be a **possibly discontinuous subset** of the option text (i.e. allow gaps), etc.

With the above, I think the US State dropdown, for example, could enable option 1, and set option 2 to **start** and you'd get the desired behavior. In addition to the current `<select>` behavior, you'd also be able to see what you're typing, not have to "rush" to type the two characters quickly, and you'd be able to edit what you've typed if you make a mistake, rather than having to wait a nebulous amount of time to let the hidden buffer "clear". The ARIA guidelines could also be easily achieved in the same manner. And those guidelines could likely drop the problematic "in rapid succession" phrase, which is itself likely an accessibility problem.

**Comment by dandclark** [comment]
@mfreed7 That all makes sense, we should certainly support textbox/listbox mode (as resolved earlier in #104 ) and given the capabilities you enumerated it seems reasonable to have the textbox/listbox mode with filtering be the default.  I still believe both of these things to be the case though:
1. The custom `<select>` anatomy should include a button/listbox mode (where there is no textbox), even though it may not be the default.  It's a common enough pattern that I expect many devs will want to use it, even if we consider textbox/listbox with filtering to be generally better.
2. If we do support a button/listbox mode, that mode should include type-to-search, because even with its deficiencies (hidden timer, can't see typed text) it's better to have it than not to have it for those users who rely on it to quickly navigate long lists.

So I'd still like to add type-to-search to the button/listbox anatomy currently at https://open-ui.org/components/select.
