### ISSUE TITLE
Handing Home/End key on Mac

### ISSUE THREAD

**Issue by dandclark** [WICG/open-ui#159]
In #156 @gregwhitworth [raised](https://github.com/WICG/open-ui/pull/156#pullrequestreview-469769879) the following point:

> On Mac they don't have home and end keys. Looking around the web it seems that if you press fn+right/left arrow it will mimic the same behavior but no browser currently implements this. I think this should be included in the PR.
> 
> Can you open an issue to discuss how to handle that divergence so the group can get agreement as we technically could keep it to home/end and OSes that don't have those keys won't receive the events. BUT, if we decide to put in the fn keys these exist on other OSes and so we should ensure that the behavior is similar there as well with regard to mimicking home/end which I doubt it does on Windows (not sure about Linux/Chromebook).
> 
> For now I'll land this PR, but we should discuss that issue in the next telecon.

When I wrote that PR I tried the fn+right/left arrow thing on a Macbook and I recall that in at least Edge/Chrome (don't remember for Safari) it worked for jumping to the first/last option.  I looked at it with a KeyDown event and the `event.key` is actually "Home"/"End" just like when the "real" keys are pressed in Windows.  If the keypress that the OS actually sends to the browser is just Home/End, then OpenUI shouldn't have to worry about handling any special behavior with fn keys because that's not what the browser platform actually sees.

I'd like to double-check this but I've since passed on the macbook I had to a coworker who needed it for something.  If someone with a Mac could confirm/deny my findings that would be great.

**Comment by gregwhitworth** [comment]
I'm actively trying it on a MacBook in Safari and Edge and it does not jump.

**Comment by chrisdholt** [comment]
@gregwhitworth are you trying on Edge Chromium on Mac? I tested this on a contribution to FAST this past week and can confirm that the fn + arrow behavior did work as home/end in that instance. @dandclark can you clarify what you’d like confirmed? That the behavior can repro on Edge Chromium or that the key represented when using that combination presents as home or end?

**Comment by gregwhitworth** [comment]
@gregwhitworth are you trying on Edge Chromium on Mac? I tested this on a contribution to FAST this past week and can confirm that the fn + arrow behavior did work as home/end in that instance.

Yep I am. And thanks for the confirmation of this because I figured out the reasoning. It only does this when the popup is open and I was testing with it closed. This highlights a variance between the controls since all browsers on Mac utilize the native select control they all repro that home and end only work when the select is open. On Windows, Chromium traverses the options (all events) when the select is closed. This becomes very apparent in that pressing the down key when the select is closed on Windows it goes to the next option while on Mac it opens the popup. Testing Firefox on Windows 10 produces the same behavior; so it really is effectively interop across the platforms.

So this now becomes an even larger question even around the general up/down events. I think we may need cross lib/native OS investigation on this to see the overlap. What the browsers do alone isn't sufficient to resolve on this.

**Comment by dandclark** [comment]
Seems like two separate questions here:
1. On Mac, do browsers receive the same KeyDown event from fn+arrow that they would get from a "real" Home/End key?  When I still had the macbook I tested [here](https://developer.mozilla.org/en-US/docs/Web/API/Document/keydown_event#addEventListener_keydown_example) and found that this appears to be true, at least as far as key events are concerned.  If the browser gets the same thing for fn+arrow as it does for "real" Home/End keys, then OpenUI shouldn't need to care about any distinction here; it can just refer to Home/End everywhere.
1. What is the right behavior for key events received by the `button` part when the `<select>` is closed, given that there are differences between browsers and OS's?

For (1), unless we have evidence that fn+arrow sends something other than Home/End to the browser, I think we should resolve that OpenUI should always just use Home/End, and close this issue.

Question (2) seems like its own investigation, unrelated to the lack of Home/End keys on Mac, that is worth opening a new Issue to track; I agree with @gregwhitworth that this likely needs further research.

**Comment by chrisdholt** [comment]
@dandclark @gregwhitworth I’m happy to check on the keyCode sent later this evening.

**Comment by chrisdholt** [comment]
> 1. On Mac, do browsers receive the same KeyDown event from fn+arrow that they would get from a "real" Home/End key?

@dandclark to the point above, it appears that the browser gets the same thing for fn + arrow keys as it does for Home/End. Confirmed on Edge for Mac:

**fn + right arrow**:
keyCode = 35
key = End

**fn + left arrow**:
keyCode = 36
key = Home

**Comment by gregwhitworth** [comment]
@chrisdholt thanks for taking a look at this. Cool, seems that this can land that PR then but we may end up changing it based on state but the behavior itself should be the same in one of those states.

@dandclark agreed, I'll file an issue
