### ISSUE TITLE
Open UI TPAC CG meeting?

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#166]
Hey everyone,

If you're planning on attending TPAC, registration opens in September (learn more [here](https://www.w3.org/2020/10/TPAC/Overview.html)). As a community group we can schedule a meeting any time for the 12-16th of October. I would be happy to schedule one for our group if there is enough desire for one an we can put together an agenda.

Please fill out the form here: https://forms.gle/a59oJq3iN8w9gUBt9

Once we get enough responses I'll update the CG and go from there.

**Comment by gregwhitworth** [comment]
Everyone, if you have agenda items please add them here

**Comment by melanierichards** [comment]
We could do a workshop to help new component libraries onboard their components to Open UI, per #129. Folks on that issue (@erikkroes, @jouni, @devongovett), is that something you'd be interested in?

**Comment by erikkroes** [comment]
Not sure what the idea is but I'd love to hear more about it.

**Comment by melanierichards** [comment]
Thanks @erikkroes!

You may be familiar with [TPAC](https://www.w3.org/2020/10/TPAC/Overview.html), but if not, it's an annual meeting of various groups within the W3C. In non-pandemic years, it's a chance for groups to get physically in the same room to hash out thornier issues, and also enables groups to have joint meetings to work on shared scenarios. Open UI will have a few hours reserved to meet online during this year's TPAC.

I was thinking that since there's a few folks who are interested in having documentation for their component libraries in Open UI, it could be neat to do a workshop at TPAC. People who are already in Open UI could do a short presentation on why it's useful to have more libraries documented, and then can quickly cover how to build the project, how all the schemas are organized, how to plug info about your component library in the right places. And then we can have an hour of working time so people can get started on their PRs, and have the opportunity to ask questions.

**Comment by erikkroes** [comment]
So basically, be available for questions? Sounds very manageable!

**Comment by erikkroes** [comment]
I'd still be interested in this workshop. Is there something I can do to make this happen?

**Comment by jouni** [comment]
Oh, I only really paid attention to this discussion today – didn’t notice I was explicitly mentioned, apologies. 

Thanks for the opportunity! I’d be happy to join if my schedule allows it. 

Do you have any more details about the potential time of day this session will be held? I’m expecting timezone differences to make this difficult for myself…

**Comment by gregwhitworth** [comment]
@jouni @erikkroes sorry for the delay here - I'll get a DOODLE up this weekend to get a time that works for everyone.

**Comment by erikkroes** [comment]
@gregwhitworth Much appreciated! I'm in CEST/UTC+2 and flexible.

**Comment by gregwhitworth** [comment]
@jouni @erikkroes here's the doodle to put in your preferred four hour block: https://doodle.com/poll/etadfeg7ya2etu5g

**Comment by erikkroes** [comment]
@gregwhitworth That was basically a choice between dinner or nighttime 😄 
I've filled in my options. The sooner I hear, the easier it is to plan. Good luck with preparations!

**Comment by erikkroes** [comment]
The 27th seems most popular. Shall I block this in my agenda? 
It requires some re-scheduling so I'd rather know sooner than later.

**Comment by gregwhitworth** [comment]
@erikkroes yeah - sorry for the delay. Just sent out the invite. DM me on twitter your email address. @jouni as well if you can. https://twitter.com/gregwhitworth
