### ISSUE TITLE
[SELECT] Open select by default

### ISSUE THREAD

**Issue by kant2002** [WICG/open-ui#229]
I notice that Uber UI has interesting property on the SELECT component - `startOpen` which displays dropdown in opened state. Again, this seems to be fringe, but at least should be considered/discussed.

Referece: https://baseweb.design/components/select/

**Comment by una** [comment]
This is an interesting point, that would also affect the popup conversation. I could see a usecase for a base open state. Added this to this week's agenda for discussion

**Comment by dandclark** [comment]
This was discussed during today's Telecon: https://www.w3.org/2020/12/03-openui-minutes.html#resolution01.
There was agreement that this is a capability worth supporting.  However rather than introducing an additional property, we resolved that the existing [open state](https://open-ui.org/components/select#open-state) should be exposed as a JS property and reflected HTML content attribute.  In addition to toggling the `<select>` open/closed programmatically, these can be used to achieve the `startOpen` behavior by e.g.:

```html
<select open>
  <option>Thing 1</option>
  <option>Thing 2</option>
</select>
```

See: https://github.com/WICG/open-ui/pull/236
