### ISSUE TITLE
[MISC] How should icons/glyphs be named?

### ISSUE THREAD

**Issue by gregwhitworth** [WICG/open-ui#27]
In issue #26 I put a strawman proposal of having a part of `icon-arrow` and this will be a common paradigm in many controls so I'd like to bring about some conformance on what these should be called. I hesitate to call them glyphs as that conflicts with text glyphs and these should not be unicode or SVG font glyphs. I would really like to defer to the design system folks that have done this many times.

@levithomason @dzearing @chrisdholt @emplums

**Comment by levithomason** [comment]
I would love to normalize icon names as well.  There sufficient icon sets around the web to fuel something like this.  It would be great to get some folks from FontAwesome to chime in as I'm sure they've done a lot of research on icon names for their project.

I imagine something like the component name matrix, but for icons.  This has always been a goal, just not something we'd added in yet.  Perhaps now is a good time to start such a table...

**Comment by chrisdholt** [comment]
@levithomason I think this could be interesting, though I do wonder how semantics will play into this. Several teams across Microsoft use a pencil for "edit"; however, from a longevity standpoint, I think that might be a mistake to standardize on. Teams at MSFT who don't have edit states may also use that specific icon/glyph to signify "pencil" or something else. 

A better example may be that in Edge, a star signifies something like a "favorite". In the Store, that same glyph might be used to signify "rating". The icons are semantic for each team and their specific application. I'm curious how we could standardize considering how often this might happen. "Star" would convey the visual of the icons and could offer alignment for both teams, but it might not end up in the table we create simply because teams are naming the glyph for their semantic scenario.

Mind you, I don't have a great solution or alternative proposal - but I'm wondering how the matrix works with the above considered? Thoughts?

**Comment by emplums** [comment]
Pinging @colebemis from our design systems team who has done a ton of work on icons :)

**Comment by colebemis** [comment]
Thanks for the ping, @emplums!

We've struggled with naming in both [Feather](https://feathericons.com) and [Octicons](https://octicons.github.com). Unfortunately, I don't have a great solution.

For Octicons, we've discussed creating some kind of alias system. An alias system would allow us to maintain generic icon names but use functional aliases for feature-specific use cases. For example, a "star" icon could be aliased to "favorite" or a "paper airplane" icon could be aliased to "send." This is similar to how we're thinking about color naming.

I think a name matrix could be helpful for standardizing generic icon names (e.g. `star`, `home`, `bell`, etc).

**Comment by gregwhitworth** [comment]
Ok, I'm going to pivot this discussion as I wasn't specifically referring to the individual icons themselves but I'll open a new one for each specific icon that we tackle. My expectation is that it will co-incide with the individual component rather than normalizing ALL icons as many libraries have thousands of icons and I don't want to get into that.

I did some research and found that the overwhelming majority of design/web libraries and design systems refer to them as icons, not glyphs. Here is what I found so you all have the same info:
| Library/Solution        | Icon | Glyph | Primary focus | Name in usage                     | HTML/CSS/JS/Graphic |
|-------------------------|------|-------|---------------|-----------------------------------|---------------------|
| [Glyphish](http://www.glyphish.com/)                | Yes  | Yes   | iOS/Mac       |                                   |                     |
| [Font Awesome](https://fontawesome.com/icons?d=gallery)            | Yes  |       | Web           | fa-<name>                         | HTML Class          |
| [FlatIcon](https://www.flaticon.com/free-icons/library)                | Yes  |       | Design        | n/a                               |                     |
| [RoundIcons](https://roundicons.com/)              | Yes  |       | Design        | n/a                               |                     |
| [Smash Icons](https://smashicons.com/)             | Yes  |       | Design        | n/a                               |                     |
| [Behance](https://www.behance.net/search/projects/?sort=appreciations&time=week&search=free%20icons)                 | Yes  |       | Design        | n/a                               |                     |
| [Pixellove](https://www.pixellove.com/)               | Yes  |       | Design        | <category>- (eg: general-cog.png) | Graphic             |
| [IconFinder](https://www.iconfinder.com/)              | Yes  |       | Design        | n/a                               |                     |
| [FreePik](https://www.freepik.com/popular-icons)                 | Yes  |       | Design        | <name>-icon                       | Graphic             |
| [Pictonic](https://pictonic.co/)                | Yes  |       | Web           | icon-<name>                       | HTML Class          |
| [IconMonstr](https://iconmonstr.com/)              | Yes  |       | Design        | iconmonstr-<name>                 | Graphic             |
| [The noun project](https://thenounproject.com/)        | Yes  |       | Design        | <location>-icon ui-<name>         | Graphic             |
| [Glyphlibrary](http://www.glyphlibrary.com/)            | Yes  | Yes   | Design        | n/a                               |                     |
| [Bootstrap](https://icons.getbootstrap.com/)               | Yes  |       | Web           | bi-<name>                         | HTML Class          |
| [Sencha JS](https://docs.sencha.com/extjs/6.0.2/guides/core_concepts/font_ext.html)               | Yes  |       | Web           | depends on library imported       | JS                  |
| [UI Kit](https://getuikit.com/docs/icon)                  | Yes  |       | Web           | uk-icon="icon: <name>"            | HTML Attribute      |
| [Groundwork CSS](https://groundworkcss.github.io/groundwork/docs/icons.html)          | Yes  |       | Web           | icon-<name>                       | HTML Class          |
| [GumbyFramework](https://gumbyframework.com/docs/ui-kit/#!/icons)          | Yes  |       | Web           | icon-<name>                       | HTML Class          |
| [Metro UI](https://metroui.org.ua/icons.html)                | Yes  |       | Web           | mif-<name>                        | HTML Class          |
| [Topcoat](https://github.com/topcoat/icons)                 | Yes  |       | Web           | topcoat-icon-<name>               | HTML Class          |
| [Onsen UI](https://onsen.io/v2/api/vue/v-ons-icon.html#icons)                | Yes  |       | Web           | icon="<name>"                     | HTML Attribute      |
| [Iconshock](https://www.iconshock.com/icon-font/)               | Yes  |       | Design        | iconshock-<name>                  | Graphic             |
| [Material WC](https://github.com/material-components/material-components-web-components/tree/master/packages/icon)             | Yes  |       | Web           | <mwc-icon>                        | Web Component       |
| [Fast DNA](https://explore.fast.design/components/action-trigger)                |      | Yes   | Web           | <TestGlyph path={"<name>"}/>      | Web Component       |
| [Fabric](https://developer.microsoft.com/en-us/fabric#/styles/web/icons)                  | Yes  |       | Web           | ms-Icon--<name>                   | HTML Class          |
|                         |      |       |               | <<Name> />                        | React Component     |
| [Lightning Design System](https://www.lightningdesignsystem.com/components/icons/) | Yes  |       | Web           | slds-icon                         | HTML Class          |
| [Carbon Design System](https://www.carbondesignsystem.com/guidelines/icons/usage/)    | Yes  | Yes   | Web           | icon--<name>                      | SVG Xlink           |

Additionally, I did a quick Twitter poll and got 115 respondants and here is the breakdown:

|Option| Percentage|
|--------|------------|
|Icon     |89.6%        |
|Glyph  |6.1%          |
|Symbol|3.5%         |
|Other  |0.9%          |

Because of this I am recommending the following proposal to avoid different specifications created by different users referring to them as different things.

**Proposed Resolution:** When referring to graphics that will be used to represent an action, location, or hint to the user the word *icon* will be used.

**Comment by levithomason** [comment]
### Icon names
@gregwhitworth it would be fantastic to get your preliminary research into a page on Open UI.  I can also look into what collecting this data might look like for something like a name matrix.

### Regarding Original Post
IMHO it would be ideal to name icon slots by their usage or intent.  This allows folks to use any icon they would like without invalidating the name.  Example, an "expand-icon" (hypothetical) will always "expand" the component (such as a tree).  The actual shape of the glyph or graphic in that slot could be a "chevron-right / chevron-down" or "plus-sign / minus-sign" (hypothetical) and still not violate the fact that it is the "icon representing the expansion of the tree item."

If we name these by their actual name ("chevron-down"), then I would think that would also necessitate disallowing changing them to another glyph.  I would also propose that they must be able to changed else folks will build their own.

This is also inline with one of Open UI's current naming principals:

>### Names should be void of design information
>
>**Why?** When designs change names should not become invalid. Names should stand the test of time. Usually, names based on intent or usage are more robust and stand this test. Consider a component that displays mock content while waiting for the actual content to load. It might be more ideally named Placeholder opposed to Shimmer, even though most implementations appears to flash or shimmer. When the design changes and these components no longer shimmer, the name will become invalid and not make sense.

We also faced this issue over the last couple years in Stardust / Fluent UI since we allowed the icon set to be swapped out as part of the "theme" definition.  However, some components internally rely on certain icons being available (i.e. a Menu Item's "indicator" icon which points in the direction of a submenu).

**Comment by levithomason** [comment]
Yep, hands down `icon` is the naturally evolved and adopted name.  Is this issue close for you @gregwhitwort?

@gregwhitworth it would be fantastic to get your preliminary research above into a page on Open UI.

**Comment by gregwhitworth** [comment]
@levithomason yeah this is closed. Currently I don't have anywhere that I reference anything that isn't icon but we'll be able to point to this in the future if people submit PRs that refer to them as anything different.

With regards to putting it up into Open UI, I'd be open to where you think it should live as it doesn't belong on any given page. I'm doing some onion peeling type research due to select and so I'm spinning up sub pages of research to inform decisions. I'd be open to hearing how you'd want general investigations like this to be placed. Possibly under the research section but on a page called Misc that links to the research page of this content?
