### ISSUE TITLE
Customizing a Textarea

### ISSUE THREAD

**Issue by stramel** [WICG/open-ui#42]
Not sure if this is the proper place to bring it up or not. Perhaps someone can point me to a good place to bring this up or a place where a conversation has already been had.

On a Textarea, it doesn't seem possible to customize the drag handle. I'm attempting to accomplish something like this. Maybe this could be improved to be easier to handle using a slot?

![image](https://user-images.githubusercontent.com/855184/72116733-cec91780-3310-11ea-8bfa-5ba843eb278f.png)

**Comment by gregwhitworth** [comment]
This is the right place for that because that isn't actually defined anywhere. That said, it will require someone doing the necessary research work for a text area to define the necessary anatomy, etc. I've added the labels to show that it needs research. Looking through the design system matrix most are listed under type `input` but still have their own unique elements or ways in which to invoke the textarea from the input.

**Comment by gregwhitworth** [comment]
Due to this not making any progress in the past few months I'm going to close this out but have placed it on our backlog.
