### ISSUE TITLE
I want to help using my project

### ISSUE THREAD

**Issue by imvetri** [WICG/open-ui#63]
I have been building https://github.com/imvetri/ui-editor to solve problems related to front end frameworks. Just wanted to share.

**Comment by gregwhitworth** [comment]
Thanks for sharing this with us @imvetri, seems like a cool project. When you say you want to help do you mean that you intend to use this as a conversion tool or that you plan to, as we get more standardization done, using the Open UI naming schemas, anatomies, behaviors in your components?

**Comment by imvetri** [comment]
I had a look at your project at hackernews. Most of the readers were complaining the project as "yet nother standard" which could be changed by showcasing what standards can offer by building more demos.

I had the same vision as your project and I was searching for solution online to find common patterns across UI, I tried to write a standard and quit it as it wasn't my area of expertise instead built a tool on top of a standard I had in mind. Open-ui.org is something which I wished I had initiated but glad that someone else did. Thanks for that.

There is some differences between the standard open-ui.org proposes and the standard ui-editor showcases. Open-ui.org focuses on standardizing naming conventions for components. Whereas ui-editor focusses on building components with a standard model/pattern.

In a way both projects are trying to standardise front end components and it shares the same vision. And I would like to offer my help by proposing standards on how to build components that scales.

Proposal for building components:

Component composition rules:

1. A component can have child component.
2. A component can be made of HTML element and a child component.
3. A component can be made of HTML element.

Message passing rules:

1. A child component may or may not receive data from parent component.
2. A child component can dispatch events which only the parent component can subscribe. Or a parent component may or may not receive child component messages.

Message passing follows rules that is similar to event propagation in web browsers. For example, in browser an event gets propagated via bubbling and cancelling. We can take inspiration from that to build a message passing model between parent and child.

This is gist of what I had in mind, I am still trying to get it in written text after multiple iterations.

**Comment by gregwhitworth** [comment]
Open UI is not solely about naming. It is about standardizing, anatomy, state, events that transition this state. What you're effectively proposing above I would expect to be covered. I have roughed out a very early draft of this for `<select>` and am digging further but the element that invokes the popup has to be listening to pointer events and keyboard ones. By then describing the anatomies this will allow web developers to adjust these as well to a varying degree. As it relates to message passing that is a good topic to discuss further. 

And yeah, I saw the Hacker news comments and I think that is where we can work a bit on the messaging of this because this is not another standard, there is no actual standard for components or else this problem wouldn't exist. As one commenter noted: "The web is the standard" and that is why I helped start up this CG in coordination with design system & framework authors. Ultimately what we define here will influence HTML/CSS WGs as I want to improve the form controls story for the web platform. But the same reasons that the web platform will benefit from this research other frameworks will as well, whether they're built in React, Vue, Angular, etc. Hopefully that clarifies things. Let me know if you have any thoughts on changes we could make to the Vision statement to make this more clear. I have this PR which tries to get a bit more granular on the specific goals: https://github.com/WICG/open-ui/pull/59

I welcome your feedback and thanks!
